numeros = []
numeros.append(3)
numeros.append(8)
numeros.append(9)
numeros.append(20)
print("Elementos del arreglo")
print(numeros)
numeros.insert(1, 15)
print(numeros)
numeros.remove(3)
print(numeros)